@startuml

class Cancion {

}

class Audio {

}

class Artista {

}

class Playlist {

}

class Album {

}

class Usuario {

}

class PlataformaMusical {

}

class Suscripcion {

}

class Genero {

}

class HistorialReproduccion {

}

class Monetizacion {

}

class Pago {

}

class Ranking {

}

class SistemaRecomendacion {

}

class AnalisisDatos {

}

class Tendencia {

}

class Reproductor {

}

' Relaciones base
Cancion *-- Audio
Playlist o-- Cancion
Album o-- Cancion
Usuario o-- HistorialReproduccion

Artista --> Cancion
Usuario --> Playlist
Usuario --> Suscripcion
Cancion --> Genero

PlataformaMusical --> Usuario
PlataformaMusical --> Monetizacion
PlataformaMusical --> SistemaRecomendacion

Monetizacion --> Pago
Ranking --> Cancion

SistemaRecomendacion --> Usuario
SistemaRecomendacion --> Cancion
SistemaRecomendacion --> AnalisisDatos

Tendencia --> Cancion

Reproductor ..> Cancion

@enduml
