  @startuml
  
  class User {
    - id : int
    - name : String
    - email : String
    - password : String
    - country: String
    - registerDate: Date
    - profiles : List‹Profile›
    - subscription : Subscription
  }
  
  class Profile {
    - id : int
    - nickname : String
    - isPrivate : Boolean
    - playlists : List‹Playlist›
    - followedArtists : List‹Artist›
    - following : List‹Profile›
    - followers : List‹Profile›
  }
  class Subscription
  class Plan
  
  class Album
  class EP
  class Song
  class Playlist
  class Single
  class Artist
  
  ' POR PARTE DEL USUARIO
  Subscription --> Plan
  User *-- Profile
  ' es el usuario o el perfil quien tiene una suscripcion?
  User *-- Subscription
  Profile ..> Subscription
  Profile o-- Playlist
  
  'COMO RED SOCIAL
  Profile --> Profile
  Profile --> Artist
  
  ' SOBRE EL CONTENIDO
  Album o-- Song
  Album <|-- EP
  Song <|-- Single
  Playlist o-- Song
  
  
  ' SOBRE AUTORIA
  Artist <--> Album
  Artist <--> Song
  
  @enduml