@startuml

hide empty members

class Artista
class Discografica
class Album
class Genero
class Cancion
class Instrumento
class Contrato
class Concierto
class Gira
class Miembro


Artista *-- Genero
Artista o-- Album
Artista o-- Cancion
Artista --> Discografica
Artista --> Artista : colaborador
Artista ..> Instrumento
Artista *-- Miembro
Artista o-- Gira
Gira o-- Concierto
Artista -- Contrato
Contrato -- Discografica

@enduml