@startuml
skinparam style strictuml
skinparam monochrome true
skinparam shadowing false
hide empty members

class Artista {
}

class Discografica {
}

class Album {
}

class Genero {
}

class Grabacion {
}

class Cancion {
}

class Compositor {
}

class Letra {
}

class Concierto {
}

Artista *-- Genero
Artista o-- Album
Artista o-- Concierto
Artista o-- Grabacion
Artista o-- Cancion
Artista o-- Letra
Artista --> Discografica
Artista --> Compositor
Artista --> Artista : amigos
Artista --> Artista : familia

@enduml