@startuml Dominio
hide empty members

abstract class Artista {
  + nombre: String
}
class Banda {
  + añoFormacion: Integer
}
class Solista {
  + nombreReal: String
}
Artista <|-- Banda
Artista <|-- Solista

class Usuario {
  + id: String
}
class UsuarioGratuito {
  + anunciosEscuchados: Integer
}
class UsuarioPremium {
  + fechaRenovacion: Date
}
Usuario <|-- UsuarioGratuito
Usuario <|-- UsuarioPremium

class Cancion {
  + titulo: String
}
class Album {
  + titulo: String
}
class Playlist {
  + nombre: String
}

Album *-- Cancion
Playlist o-- Cancion
Usuario --> Artista : sigue a
Usuario --> Usuario : amigos

@enduml