@startuml

class Plataforma
class Estadistica
class Reproduccion
class Oyente
class Playlist
class Reproductor
class Cancion
class Partitura
class Nota
class GeneroMusical
class Letra
class Productor
class Album
class Banda
class Artista
class Instrumento

' --- COMPOSICIÓN ---
Plataforma *-- Oyente : aloja 
Plataforma *-- Estadistica : calcula 
Oyente *-- Playlist : posee 
Partitura *-- Nota : contiene 

' --- AGREGACIÓN ---
Banda o-- Artista : agrupa 
Album o-- Cancion : contiene 
Playlist o-- Cancion : recopila 
Cancion o-- Letra : tiene 
Cancion o-- Partitura : transcrita en 
Cancion o-- GeneroMusical : clasificada en 
Cancion o-- Productor : producida por 
Cancion o-- Artista : interpretada por 

' --- USO ---
Oyente ..> Reproductor : usa 
Oyente ..> Reproduccion : genera 
Reproduccion ..> Cancion : procesa 
Artista ..> Instrumento : toca 

@enduml