@startuml

skinparam classAttributeIconSize 0

' --- ENUMS ---
enum TipoSuscripcion {
}

enum EstadoSuscripcion {
}

' --- CLASES ---
class Usuario {
}

class Suscripcion {
}

class Playlist {
}

class Artista {
}

class Album {
}

class Cancion {
}

class PistaAudio {
}

' --- RELACIONES ---

Usuario *-- Suscripcion
Suscripcion --> TipoSuscripcion
Suscripcion --> EstadoSuscripcion

Usuario *-- Playlist
Usuario --> Playlist
Usuario --> Artista
Usuario --> Cancion

Artista --> Album
Artista --> Cancion

Album o-- Cancion
Playlist o-- Cancion

Cancion *-- PistaAudio

@enduml