@startuml

hide empty members

class Persona{
}

class Nombre{
}

class Apellido{
}

class Edad{
}

class Genero{
}

class DNI{
}

class Religion{
}

class EducacionAcademica{
}

class Gusto{
}

class Caracter{
}

class Nacionalidad{
}

class RasgoFisico{
}

class Idioma{
}

class Profesion{
}

Persona *-- Caracter
Persona *-- Edad
Persona *-- Genero
Persona *-- RasgoFisico
Persona o-- Nombre
Persona o-- Apellido
Persona o-- Nacionalidad
Persona o-- Idioma
Persona o-- EducacionAcademica
Persona --> Religion
Persona --> Persona : amigos
Persona --> Persona : familia
Persona --> Profesion
Persona ..> Gusto
Persona --> DNI

@enduml